# -*- coding: utf-8 -*-
"""script.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f2AtoHxqAHI5JJ1mJF7BsV-MclZ9Pjgd
"""

#########
#"""Character setup, Intro script, etc."""
#########
# The script of the game goes in this file.

# Declare all characters

define romeo_father = Character("Julio Gonzalez")
define romeo = Character("Romeo Gonzalez")
define player = Character("Player", what_italic=True)
define r = Character("Ricardo")
define y = Character()
define g = Character(what_italic=True)
define jf = Character("Julieta", color = "#ffc0cb")
define blnca = Character("Blanca", color = "#ffffff")
define dm = Character("Dolores")
define ig = Character("Iglesias")

# Declare menuset
default menuset = set()



# The game starts here.

label start:
    # Non-room related flags
    $ selected_murdurer = -1

    # JULIO GONZALEZ's boolean flags
    $ baking_soda = False
    $ mug = False
    $ documents_observed = False
    $ visited_crime_scene = False
    $ visited_jorge_room = False

    # RICARDO FERNANDEZ'S boolean flags
    define visited_parlor = False
    define ricardo_quipnum = 0
    define ricardo_quip = ""
    define ball_needed = False
    define billiard_ball = False
    define inquired = False

    # ROMERO GONZALEZ'S boolean flags
    default visited_romero = False
    default vial = False
    default science_journal = False
    default letter_from_julieta = False
    default torn_page = False
    default herbs = False
    default government_book = False
    default relationship_with_father = False
    default neck_scar = False
    default romero_julieta_painting = False

    # JULIETA FERNANDEZ'S boolean flags
    default visited_julieta_room = False
    default notebook = False
    default dress = False
    default cat_bed = False
    default talked_julieta = False
    default looked_julieta = False

    #FLAGS DE DOLORES DE MURO
    default visited_Dolores_room = False
    default speak_freely = True
    default kicked_out = False
    default bag_permission = False
    default dolores_introduced = False
    default read_dolores_letter = False
    default read_dolores_books = False

# Start intro script
    player "Placeholder intro text"
    # End intro script

    jump global_room

#########
#"""Global Room Menu"""
#########

label global_room:
    menu global_room_menu:
        "Who should I investigate?"

        "Julieta Fernandez":
            jump julieta_start
        "Lorenzo Fernandez":
            jump lorenzo_start
        "Ricardo Fernandez":
            jump parlor_start
        "Romero Gonzalez":
            jump romero_start
        "Julio Gonzalez":
            jump romeo_father_start
        "Dolores de Muro":
            pass
        "Iglesias":
            jump iglesias_start
        "Done investigating":
            player "Is this it? Do I have enough evidence to make a judgment?"
            menu:
                "Yes, I'm done!":
                    jump end_chapter # finished investigating
                "No, not yet!":
                    jump global_room_menu

#########
#"""JULIETA FERNANDEZ"""
#########

label julieta_start:

    scene bg julietas_room

    if not visited_julieta_room:
        player  "(Jeez. I get that these people are rich but this room is absolutely lavish.)"
        player  "(And excessivly pink.)"

        show Julieta

        jf "HISSSSSSSSSSS!"
        player  "AHHHHHH!"
        jf "Hey creep! What are you doing in my room?"
        player  "(Did she just hiss at me?)"
        player  "(And who is she calling creep?)"
        player  "Young Lady, I am a government official."
        player  "I'm currently conducting an investigation on the death of Jorge Gonzalez."
        jf "..."
        jf "Fine, but you better not leave any of your old person smell anywhere."
        jf "My dear Blanca aboslutely hates gross smells."
        blnca "Meeeooow!"
        player  "(I didn't even notice the cat.)"
        player  "(They aren't common pets around here, she really is from a rich family)"
        player  "(And I'm just goning to ignore her other comment)"
        player  "Lets start with a few basic questions."
        player  "What is your name and occupation?"
        jf "My name is Julieta Fernandez, soon-to-be bride of the most perfect and handsome man on the planet!"
        player  "Huh!? Who are you talking about?"
        jf "Romero Fernandez, you idiot! The perfect man and heir to the Fernandez Family!"
        player  "(She's in love with the son of the the Fernandez family?)"
        player  "(I thought these two families absolutely hated eath other.)"
        player  "(Well whatever, it's about time I get this investigation under way.)"

    else:
        show Julieta

        jf "Ugh. Why did you come back? The awful smell had just cleard up."
        player  "(Trust me, I wouldn't be here if I didn't need to be.)"
        player  "(And why does she keep saying I smell?)"

    menu julieta_investigation_choices:
            player  "(What should I do?)"

            "Talk to Julieta.":
                if not talked_julieta:
                    jump talking_with_julieta
                else:
                    jump talking_choices

            "Look around room.":
                if not looked_julieta:
                    jump looking_around_room
                else:
                    jump julieta_room_examination

            "Leave room.":
                hide Julieta
                player  "(I guess that's all I could find here for now.)"
                player  "(I should try looking somwhere else.)"
                $ visited_julieta_room = True
                jump global_room_menu

    # Talking with Julieta section

    label talking_with_julieta:
        player  "I'd like to ask you some more questions."

        jf "Fine, but it better be quick, I can smell you from here."

        player  "(I should take her in just for that!)"
        player  "(Sigh. Keep it together, there are more important things to worry about.)"

        menu julieta_talking_choices:

            set menuset
            player  "(What should I ask her about?)"

            "Ask about Romero.":
                jump jaromero

            "Ask about her father." if visited_lorenzo_room or dress:
                jump jafather

            "Ask about her brother." if visited_parlor:
                jump jabrother

            "Ask about the victim.":
                jump javictim

            "Ask about Blanca.":
                jump jablanca

        player  "(There isn't anything else to ask her about.)"
        player  "(I could try again later if I learn more information.)"
        $ talked_julieta = True
        jump julieta_investigation_choices

        label jaromero:
            player  "You mentioned that you were going to marry Romero Gonzalez."
            player  "Can you tell me more about him?"
            jf "Romero is my knight in shining armor. I want to be with him for the rest of my life!"
            jf "His chiseled face is sculpted by the gods!!~"
            player  "(Sigh. Well she certainly loves him. Maybe a bit too much.)"
            jump julieta_talking_choices

        label jafather:
            player  "(I ask aboout Lorenzo Fernandez.)"
            jump julieta_talking_choices

        label jabrother:
            player  "(I ask about Ricardo Fernandez.)"
            jump julieta_talking_choices

        label javictim:
            player  "(I ask about Jorge Gonzalez.)"
            jump julieta_talking_choices

        label jablanca:
            player  "(I ask about her cat. Why am I doing this?)"
            jump julieta_talking_choices

    # Looking around the room section

    label looking_around_room:
        player  "I'd like to look around your room for anything related to the case."

        jf "Fine, but you better not touch anything you're not supposed to you smelly pervert."
        jf "Or else you'll have to talk with Blanca and me."

        blnca "HISSSSSSSSSSS!"

        player  "(I better make this quick, I don't want to have my eyes clawed out by this crazy beast.)"
        player  "(Or her cat.)"
        hide Julieta

        menu julieta_room_examination:

            set menuset
            player  "Where should I look?"

            "Look at closet":
                jump jicloset

            "Look at desk":
                jump jidesk

            "Look at bed":
                jump jibed

            "Look at cat bed":
                jump jicbed

            "Look at bookshelf":
                jump jibookshelf


        player  "(It seems like I've examined everything in this room, I should try something else.)"
        $ looked_julieta = True
        show Julieta
        jump julieta_investigation_choices

        label jicloset:
            player  "(I look at the closet with the dress in it)"
            $ dress = True
            jump julieta_room_examination

        label jidesk:
            player  "(Love letters and notebook)"
            $ notebook = True
            jump julieta_room_examination

        label jibed:
            player  "(large pink bed looked at)"
            jump julieta_room_examination

        label jicbed:
            player  "(look at cat bed with a collection of odd objects on it.)"
            $ cat_bed = True
            jump julieta_room_examination

        label jibookshelf:
            player  "(look at bookshelf, there are lots of romance novels.)"
            jump julieta_room_examination

#########
#"""LORENZO FERNANDEZ"""
# Declare characters used by this game. The color argument colorizes the
# name of the character.


# TODO: match players with global vars

image BGroom = "library-1219676-1920x1440.jpg"
image Lorenzo = "jacob.png"
image envelope = "classified-1241157-1920x1440"
image weapon = "revolver-1176758-1919x1284.jpg"
image bibleimg = "very-old-family-bible-1-1494754"
image drugimg = "ancient-book-pt-2-1512285-1920x1440"

define player = Character("Player", what_italic = True)
define romeo_father = Character("Julio Gonzalez")
define romeo = Character("Romeo Gonzalez")
define teacher = Character ("Dolore De Muro")
define iglesias = Character ("Iglesias")
define juliet_father = Character("Lorenzo Fernandez")
define julieta = Character("Julieta Fernandez")
define Juliet_brother= Character("Ricardo Fernandezz")



# The game starts here.

label lorenzo_start:



    scene BGroom

    "You entered Lorenzo Fernandez's study room."
    menu choices:
        "(To Lorenzo Fernandez)Would you please introduce yourself?":
            jump q1
        "(To Lorenzo Fernandez)How’s your relationship with Gonzalez's family?":
            jump q2
        "(To Lorenzo Fernandez)Do you know the relationship between Romeo and Juliet?":
            jump q3
        "(To Lorenzo Fernandez)Do you support the marriage? ":
            jump q4
        "(To Lorenzo Fernandez)Do you know Jorge Gonzalez had been killed?":
            jump q5
        "Search the room":
            jump search
        # "Return to the lobby"
        #     jump lobby

    label q1:
        show Lorenzo
        juliet_father "You dare to enter this room without knowing who I am?"
        "Lorenzo Fernandez's body guard send you out of the room."
        return
    label q2:
        show Lorenzo
        juliet_father "You probably should know the relationship isn’t good
                        with our standing rivalry between each other.
                        Recently they have been an extra thorn in my side. "
        hide Lorenzo
        jump choices
    label q3:
        show Lorenzo
        juliet_father "I believe I do."
        hide Lorenzo
        jump choices
    label q4:
        show Lorenzo
        juliet_father"This marriage has my blessing. "
        hide Lorenzo
        jump choices
    label q5:
        show Lorenzo
        juliet_father"No, I left shortly after he fainted."
        hide Lorenzo
        jump choices
    ####################################################################
    menu search:
        "Gun":
            jump gun
        "Letter":
            jump letter
        "Bible":
            jump bible
        "Return to the choice menu.":
            jump choices

    label gun:
        show weapon
        "You found a gun inside the draw, do you want check the gun?"
        menu check1:
            "Yes":
                hide weapon
                jump Yes1
            "No":
                hide weapon
                jump No1
        label Yes1:
            show Lorenzo
            juliet_father"You dare touch my weapon?"
            "Lorenzo Fernandez's body guard send you out of the room."
            return
        label No1:
            jump search

    label letter:
        show envelope
        "You found a letter from Romeo for the marriage approval."
        hide envelope
        jump search

    label bible:
        show bibleimg
        "You found a Bible, do you want open it?"
        hide bibleimg
        menu check2:
            "Yes":
                jump Yes2
            "No":
                jump No2
        label Yes2:
            show drugimg
            "You found a drug recipe teaches how to make sleeping pills into poison."
            hide drugimg
            jump search
        label No2:
            jump search
    # This ends the game.

    return
#########

#########
#"""RICARDO FERNANDEZ"""
#########
label parlor_start:
    scene parlor



    show ricardo



    if visited_parlor == False:
        g "You enter the parlor. The smell of cigarettes lingers in the air. A man is sitting next to the pool table.
        He ashes his cigarette as you walk over."
        r "Oh, you're the official who came validate father's land claim."
        r "Such a shame what happened to the head of the Gonzalez family."
        r "Can't say I knew the guy very well, though."
        y "Who are you?"
        r "Name's Ricardo, I'm Julieta's older brother."
        $ visited_parlor = True

    menu Decision:
        "What should I do?"

        "Speak to Ricardo":
            $ ricardo_quipnum = renpy.random.randint(1,3)
            if ricardo_quipnum == 1:
                $ ricardo_quip = "Did you need something?"
            if ricardo_quipnum == 2:
                $ ricardo_quip = "Want to go a round on the table?"
            if ricardo_quipnum == 3:
                $ ricardo_quip = "You want a smoke? These have the highest quality tabacco you can find in 'em."
            jump ricardo_talk
        "Look around":
            "The parlor is hazy with smoke. The pool table has billiard balls strewn about."
            "Ricardo was most likely playing by himself."
            "The only pocketed ball is the white one. He must not be very good."
            jump Decision
        "Leave Room":
            jump global_room
    menu ricardo_talk:
        "[ricardo_quip]"
        "Tell me about yourself.":
            r "Why do you want to know about me? Oh, whatever. I've been bored with these families
            going on and on about who's land is who's. I suppose some conversation wouldn't hurt."
            jump ricardo_talk

        "Inquire about Jorge's death.":
            y "Do you know anything about what happened to Mr. Gonzalez?"
            r "Nothing important, I don't think. I know he didn't get along with my father."
            y "I see."
            r "..."
            r "Actually I've just thought of something strange I overheard, but I'm
            fairly certain it was a private matter."
            y "Please tell me anything you know. Information on the cause of Jorge's death
            could affect the rights to this land."
            r "Well, I'm not so unloyal to my family as to let internal matters known to outsiders,
            though I'm not the biggest fan of the way father acts towards me."
            r "Tell you what, you beat me in a match of billiards and I'll tell you something
            I overheard my father say."
            g "This works out nicely. I'm confident in my billiards abilities."
            y "Deal."
            r "The only issue is this table is missing a ball. How one could misplace a billiard
            ball is beyond me."
            if billiard_ball:
                g "A missing billiard ball? I should show him the one I found."
            else:
                g "So I just need to find a billiard ball? I guess I should scour the mansion."
            $ inquired = True
            jump ricardo_talk

        "Show Ricardo the billiard ball." if (inquired and billiard_ball):
            y "I found the ball."
            r "Wow, I didn't expect you to actually go out of your way to find it! Well, are you ready to lose
            to the great Ricardo? I've been practicing while holed up in this mansion."
            g "I dominated Ricardo in a game of pool. And in the ensuing rematches."
            jump ricardo_talk


        "Never Mind.":
            jump Decision

#########
#"""ROMERO GONZALEZ"""
#########
if not dolores_introduced:
    pass
label romero_start:
    scene bg romero_room
    with dissolve

    show romero

#########
#"""JULIO GONZALEZ"""
#########
label romeo_father_start:
    scene bg room

    #show makoto serious

    #play music "audio/lesson.mp3"

    player "So it looks like [romeo_father.name] has died of something..."

    player "I wonder what I should observe first..."

label romeo_father_menu:
    scene bg room

    menu:
        "What should I observe?"
        "The crime scene":
            jump romeo_father_crimescene
        "[romeo_father.name]'s room":
            jump romeo_father_roomscene
        "I'm done":
            jump romeo_father_end

label romeo_father_crimescene:
    scene romeo father crimescene
    $ visited_crimescene = True
    player "So this is where [romeo_father.name] died mysteriously..."
    player "I think I should investigate the body and his surroundings."
    menu romeo_father_crimescene_menu:
        "Investigate body":
            jump romeo_father_crimescene_body
        "Investigate surroundings":
            jump romeo_father_crimescene_surroundings
        "Leave crime scene":
            jump romeo_father_menu


    player "I think I've investigated the entire crime scene.\
    I don't need to be here anymore."
    jump romeo_father_menu


    label romeo_father_crimescene_body:

        menu romeo_father_crimescene_body_menu:
            set menuset
            "Which part of the body should I investigate?"

            "Hands":
                player "There's some liquid left on [romeo_father.name]'s hands..."
                player "Was he sweating that hard?"
                jump romeo_father_crimescene_body_menu
            "Feet":
                player "He's actually got really nice shoes on his big feet."
                player "I wonder if he got them through the black market."
                jump romeo_father_crimescene_body_menu
            "Head":
                player "I can see the veins popping out of his head..."
                player "Could it be from all the stress?"
                jump romeo_father_crimescene_body_menu
            "Mouth":
                player "His lips seem to be burnt purple..."
                player "Is this the sign of royalty?"
                player "...NO! There has to be a reason behind this..."
                jump romeo_father_crimescene_body_menu
            "Chest":
                player "Is there a chance he's still alive?"
                player "..."
                player "...no pulse. It's way too late to revive him."
                jump romeo_father_crimescene_body_menu

        player "Hmm, that's all the info I can get from the body."
        jump romeo_father_crimescene_menu

    label romeo_father_crimescene_surroundings:
        scene romeo father crimescene
        player "So here is the crime scene..."

        menu romeo_father_crimescene_surroundings_menu:
            set menuset
            "What should I inspect first?"

            "Documents":
                $ documents = True
                player "Looks like this is a document about the impending sale of [romeo_father.name]'s land."
                player "I can't imagine how much stress this could be..."
                player "I don't think I would have signed these documents either, to sell family fortunes like that..."
                jump romeo_father_crimescene_surroundings_menu
            "Mug":
                player "Why does [romeo_father.name] like drinking out of mugs?"
                # based on prev. conversation with Romeo, player could know the answer
                # TODO: talk to Romeo about this conversation
                #if romeo_drink:
                #    player "Oh yeah! [romeo.name] told me that he likes to drink margaritas!"
                #    player "But is that what he was drinking in this mug?"
                #else:
                player "Is he drinking a margarita or something?"
                player "Does he have a drinking addiction?"
                player "He must have been stressed out..."
                $ mug = True
                jump romeo_father_crimescene_surroundings_menu
            "Pen":
                player "Was he about to sign the sale documents?"
                player "I thought he was trying to dispute the sale."
                player "Or were they ready to come up with a compromise?"
                player "Either way, that's a lot of ink for one document..."
                jump romeo_father_crimescene_surroundings_menu

        player "Hmm, there's nothing else to investigate here."
        jump romeo_father_crimescene_menu

label romeo_father_roomscene:
    scene romeo father room
    $ visited_jorge_room = True
    player "So this is [romeo_father.name]'s break room for the meeting..."

    menu romeo_father_roomscene_menu:
        set menuset
        "What should I observe here in [romeo_father.name]'s room?"

        "Bookshelf":
            #alchemist books, land ownership books
            player "[romeo_father.name] really likes to read books.
            He brought so many books with him to fill a bookshelf!"
            player "Looks like this is a book is titled \"Traité Élémentaire de Chimie.\"."
            player "Must be something about the chimneys he's about to build on his land."
            player "Wait, is that a book about volcanoes?"
            $ baking_soda = True
            player "I love mixing baking soda with my vinegar! What a mass solution!"
            jump romeo_father_roomscene_menu
        "Desk":
            #have some alchemist stuff (reference to teacher and Romeo)
            player "[romeo_father.name]'s desk is rather clean."
            player "I'm sure [romeo] picked up some habits from his father."
            player "Hm? Is this a new recipe for bread?"
            if baking_soda:
                player "Of course! That's what the baking soda was for!"
                player "But why was he trying to learn how to bake bread?"
            else:
                player "That certainly makes my tummy growl."
            jump romeo_father_roomscene_menu
        "Bed":
            #stains, bad lead towards poison
            #made bed
            player "[romeo_father.name] seems like a very neat guy. He's a grown man;
            he can make his own bed."
            player "...hmm? Why are the pillows stained?"
            if baking_soda:
                player "Is this the baking soda from his volcano experiments?"
            if mug:
                player "Is it his margarita from his mug again?"
            player "I wouldn't see any other reason..."
            jump romeo_father_roomscene_menu

    player "Hmm, that's all there is to observe in this room."
    jump romeo_father_menu

label romeo_father_end:
    player "Yeah, I suppose there's nothing else to do here. Let's check out the other evidence."
    jump global_room_menu

#########
#"""DOLORES DE MURO"""
#########
if not dolores_introduced:
  jump dolores_menu

label dolores_start:
  "By the window you see a small and simply dressed woman. She stares  into the courtyard which stays lit by the light of the pale moon."
  "Her eyes, wide but empty, sit on a face held on folded hands. She doesn’t move, but finds you in her notice."
  dm "I am Dolores de Muro. Teacher for the son of The Late Master Gonzales. You are the government negotiator, correct?"
  dm "How goes your search sir?"
  menu intro1:
    set menuset

    "pass":
        pass

label dolores_menu:

#########
#"""IGLESIAS"""
#########

label iglesias_start:
    # show ig's room
    # scene bg ig_start

    # bg mucis
    # play bg

    # show player
    show player at left
    with dissolve


    player """
    So here is Iglesias's room.

    They said Iglesias is a writer and a historian,

    maybe I can find something others don't want to tell me.

    Or perhaps there are some secrets recorded by Iglesias and I find out some clues.
    """

    hide player

    # Test1: test if player would like to be rude and check Iglesias's table
    # if player is rude the main information the player will get is limited
    # if player is not rude, based on his clues the player get from others,
    #   the player are allowed to know more.

    # show ig's messy table and room here
    # scene ig_meesy_room

    show player at left
    with dissolve
    player "(Looks like Iglesias is not here right now.)"
    hide player

    show ig_table at center
    with dissolve
    player "(There are some pieces of paper over there.)"
    hide ig_table

    show ig_bookshelf at center
    with dissolve
    player "(Look, these notebooks are classificated by family names.)"
    hide ig_bookshelf

    # player's choice
    menu:
        player "(I should wait Iglesias or try to find out something before he comes?)"
        "Maybe I can find something here.":
            jump iglesias_room
        "Maybe I should wait Iglesias.":
            jump iglesias_meet


label iglesias_room:
    menu ig_room_menu:
        set menuset
        "Which I should start from?"

        "Paper on that table":
            player "Let's see what I can find here."
            # show ig_paper_1 at truecenter
            # with dissolve
            player "Oh, what the next page will have?"

            ig """
            Last week, Romero came and had a talk with me.

            He wondered why Jorge could not understand his plans.

            I know that He must be blamed by Jorge a few minutes ago.

            I told him: Don't give up. Just keep working hard.
            Jorge will know what your efforts means to the family

            Romero left with the words: I hate my father.
            """
            # hide ig_paper_1

            player "Emm, Romero had some problems with his father"

            player "Let's see what the next page says."

            ig """
            Jorge discussed the marriage with me last month.

            He said he just met with Lorenzo the day before he came to see me.

            He said Lorenzo was going too far!
            He know he can't win the contest about this island so he told me that.

            The only condition Julieta could
            marry Romero is we have to give up this contest.

            """

            # show ig_paper_2 at truecenter
            # with dissolve
            # play footstep
            # hide ig_paper_2
            player "Damn, He's back."
            jump iglesias_rude_meet

        "Bookself":
            player "Let's see what I can find here."
            # show ig_book_1 at truecenter
            # with dissolve
            # should be the history of Gonzalez to point out this family is a up=rising star
            ig """
            Gonzalez Family:

            """

            player "So, this is Gonzalez history books. What will Fernandez books say"
            # to point out Fernadez family is declining overlord
            ig """
            Fernandez Family:
            """
            # play footstep

            player "Damn, He's back."
            jump iglesias_rude_meet

label iglesias_meet:

    show ig_p at right
    with dissolve
    ig "Oh, officer, you are here. I thought you might ask me to meet you ar the Congress Hall."
    ig "What I can help you?"
    hide ig_p

    show player at left
    with dissolve
    player """
    I am sorry about the death of Jorge Gonzalez.
    I know you are the close acquaintance of him.

    I want to know is there any thing you know relate this murder
    """
    hide player

    show ig_p at right
    with dissolve
    ig """
    Thank you for your efforts to find out the murderer. I want to find out the murderer too.

    However, the problem is I don't find out any clues by myslef.

    You know I am a historian. History could always help us.

    Is there any thing about the Gonzalez family and Fernandez family you want to know.

    I will tell you everythin I know.
    """
    hide ig_p

    jump iglesias_qa

label iglesias_qa:

    menu ig_qa_menu:
        set menuset
        "What you want to know?"

        "Julieta Fernandez":
            jump ig_jf_qa
        "Lorenzo Fernandez":
            jump ig_lf_qa
        "Ricardo Fernandez":
            jump ig_rg_qa
        "Romero Gonzalez":
            jump ig_rg_qa
        "Jorge Gonzalez":
            jump ig_jg_qa
        "Dolores de Muro":
            jump ig_dm_qa
        "I think I got enough information":
            show player at left
            with dissolve
            player "Thank you Iglesias, I think I got enouth information I need."
            hide player

            show ig_p at right
            with dissolve
            ig "Hope you can find that murderer out. "

            jump iglesias_end

label ig_jf_qa:
    show player at left
    with dissolve
    player "I want to know something about Julieta Fernandez."
    hide player

    show ig_p at right
    with dissolve
    ig """
    Oh, Juliete is a nice girl. Maybe you don't know it.

    When Romero meet Julieta for the first time, they don't knwo each other's family.

    Since that time. they start to fall in love.
    """
    hide ig_p

    jump ig_qa_menu

label ig_lf_qa:
    show player at left
    with dissolve
    player "I want to know something about Lorenzo Fernandez."
    hide player

    show ig_p at right
    with dissolve
    ig """
    Oh, Loranzo Fernandez. He is a ambitious guy. You may not know it.

    Fernandez family used to be the overlord of  northern Mexico City for last 200 years.

    For unkonw reason, in the last 60 years, they start to decline to the situation you can see right now.

    Loranzo wants to bring Fernandez family back to they used to be 200 years ago.

    Even sometimes he may did something radical, but I need to admit that he is talented,
    and Fernandez family is much better than 10 years ago.
    """
    hide ig_p

    jump ig_qa_menu

label ig_rf_qa:
    show player at left
    with dissolve
    player "I want to know something about Ricardo Fernandez."
    hide player

    show ig_p at right
    with dissolve
    ig """
    To be honest, I don't like Ricardo Fernandez.

    He is just a balck sheep and I don'know a lot about him.

    But it might be reasonable for him to do something ridiculous.
    """
    hide ig_p

    jump ig_qa_menu

label ig_rg_qa:
    show player at left
    with dissolve
    player "I want to know something about Romero Gonzalez."
    hide player

    show ig_p at right
    with dissolve
    ig """
    Oh, my boy Romero. He is such a gifted young guy. He always come to see me.

    Sometimes he comes with foods, somethimes he comes with questions, sometimes he comes with complaint.

    His ideas might be too creative for his father, so they always have some family squablle.
    """
    hide ig_p

    jump ig_qa_menu

label ig_jg_qa:
    show player at left
    with dissolve
    player "I want to know something about Jorge Gonzalez."
    hide player

    show ig_p at right
    with dissolve
    ig """
    Oh my friend Jorge. He was a good man for all his life.

    ...

    You must know that, the two families are talking about the marriage of Romero and Julieta.

    My friend Jorge likes Julieta so much. He belief that she will be a good daughter-in-law
    and may bring these two family a peace relationship.

    The reason why the marraige come to nothing is Lorenzo was pushing Jorge too far.

    Loranzo wants Jorge to give up this island.

    Alas! Rest in peace, my frind Jorge.
    """
    hide ig_p

    jump ig_qa_menu

label ig_dm_qa:
    show player at left
    with dissolve
    player "I want to know something about Dolores de Muro."
    hide player

    show ig_p at right
    with dissolve
    ig """
    I don't know that guy a lot. All I know is he is Romero's teacher.

    But I heared other people said that His village property were seized by Jorge.

    He'll be a bit of suspect.
    """
    hide ig_p

    jump ig_qa_menu

label iglesias_rude_meet:
    show ig_p at right
    with dissolve
    ig "Oh, officer, you are here. I thought you might ask me to meet you ar the Congress Hall."
    ig "What I can help you?"
    hide ig_p
    #player footstep
    show ig_room_changed
    with dissolve
    ig "Psst..."
    hide ig_room_changed

    show ig_chair at right
    with dissolve

    ig """
    Bah!

    You moved my stuff !!!

    Since you've already get what you want,

    Get out of my room !!!

    How rude you are !!!
    """

label iglesias_end:
    show player at left
    with dissolve
    player "(It looks like these are what I can find here)"
    jump global_room_menu

#########
#"""CONCLUSION SCENE"""
#########

label end_chapter:
    player "So, who committed the murder?"

    menu murder_menu:
        "Who committed the murder?"

        "Julieta Fernandez":
            $ selected_murdurer = 1
            pass
        "Lorenzo Fernandez":
            $ selected_murdurer = 2
            pass
        "Ricardo Fernandez":
            $ selected_murdurer = 3
            pass
        "Romero Gonzalez":
            $ selected_murdurer = 4
            pass
        "Julio Gonzalez":
            $ selected_murdurer = 5
            pass
        "Dolores de Muro":
            $ selected_murdurer = 6
            pass
        "Iglesias":
            $ selected_murdurer = 7
            pass

    pass

    return
